# -*- coding: utf-8 -*-
"""Python basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7RxsmiYUZJLspXIvOT1J-M1YKH8D2hq
"""

class FlashDriven:
    NoFlashDrive = 1

    def __init__(self,NoFlashDrive = 1):
        self.NoFlashDrive = NoFlashDrive
    def NoFlashDrive(self):
        print("No Flash Drive")
    def FlashDrive(self):
        print(f"Flash Drive is {self.NoFlashDrive}")

